version: '3.8'

services:
  app1:
    build: ./app1
    container_name: container1
    networks:
      - network_ubuntu
    volumes:
      - ./app1:/app1
  app2:
    build: ./app2
    container_name: container2
    networks:
      - network_ubuntu
    volumes:
      - ./app2:/app2
networks:
  network_ubuntu:
    driver: bridge