version: '3.8'

services:
  app1:
    build: ./app1
    container_name: container1
    networks:
      - my_network

  app2:
    build: ./app2
    container_name: container2
    networks:
      - my_network

networks:
  my_network:
    driver: bridge